version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/url_shortener
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
